"""add workspace invite code

Revision ID: 26904cf682b7
Revises: b9e49c30b2c7
Create Date: 2026-08-12 15:16:00.127275

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26904cf682b7"
down_revision: str | None = "b9e49c30b2c7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workspaces", sa.Column("invite_code", sa.String(length=20), nullable=True))
    op.create_index(op.f("ix_workspaces_invite_code"), "workspaces", ["invite_code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspaces_invite_code"), table_name="workspaces")
    op.drop_column("workspaces", "invite_code")
    # ### end Alembic commands ###
