"""initial schema

Revision ID: b9e49c30b2c7
Revises: 
Create Date: 2026-08-12 05:36:59.384487

"""
from collections.abc import Sequence

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9e49c30b2c7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('api_keys',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_workspace_id'), 'api_keys', ['workspace_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_workspace_id'), 'audit_log', ['workspace_id'], unique=False)
    op.create_table('eval_cases',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('incident_text', sa.String(), nullable=False),
    sa.Column('expected_postmortem_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('expected_service_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_cases_workspace_id'), 'eval_cases', ['workspace_id'], unique=False)
    op.create_table('eval_runs',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recall_at_1', sa.Float(), nullable=True),
    sa.Column('recall_at_5', sa.Float(), nullable=True),
    sa.Column('mrr', sa.Float(), nullable=True),
    sa.Column('groundedness', sa.Float(), nullable=True),
    sa.Column('citation_validity', sa.Float(), nullable=True),
    sa.Column('cases_run', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_runs_workspace_id'), 'eval_runs', ['workspace_id'], unique=False)
    op.create_table('failure_modes',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('canonical_description', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'label', name='uq_failure_modes_workspace_label')
    )
    op.create_index(op.f('ix_failure_modes_workspace_id'), 'failure_modes', ['workspace_id'], unique=False)
    op.create_table('incidents',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('raw_alert_text', sa.String(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('open', 'mitigated', 'resolved', 'false_positive', name='incident_status'), nullable=False),
    sa.Column('opened_by', sa.UUID(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_workspace_id'), 'incidents', ['workspace_id'], unique=False)
    op.create_index('ix_incidents_workspace_status', 'incidents', ['workspace_id', 'status'], unique=False)
    op.create_table('jobs',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', 'dead', name='job_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sa.String(length=200), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_claim_queue', 'jobs', ['status', 'run_after'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_index(op.f('ix_jobs_workspace_id'), 'jobs', ['workspace_id'], unique=False)
    op.create_table('postmortems',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('sev1', 'sev2', 'sev3', 'sev4', name='severity'), nullable=True),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('redacted_text', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'indexed', 'failed', name='postmortem_status'), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('injection_flagged', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postmortems_workspace_id'), 'postmortems', ['workspace_id'], unique=False)
    op.create_index('ix_postmortems_workspace_status', 'postmortems', ['workspace_id', 'status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('semantic_cache',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('prompt_hash', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semantic_cache_prompt_hash'), 'semantic_cache', ['prompt_hash'], unique=False)
    op.create_index(op.f('ix_semantic_cache_workspace_id'), 'semantic_cache', ['workspace_id'], unique=False)
    op.create_table('teams',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slack_handle', sa.String(length=200), nullable=True),
    sa.Column('escalation_contact', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_workspace_id'), 'teams', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'responder', 'viewer', name='workspace_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id')
    )
    op.create_table('agent_runs',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('graph_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_tokens_in', sa.Integer(), nullable=False),
    sa.Column('total_tokens_out', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_incident_id'), 'agent_runs', ['incident_id'], unique=False)
    op.create_table('briefs',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('generating', 'ready', 'failed', name='brief_status'), nullable=False),
    sa.Column('hypotheses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched_postmortems', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blast_radius', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('runbook_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('page_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('correction_passes', sa.Integer(), nullable=False),
    sa.Column('llm_used', sa.Boolean(), nullable=False),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_briefs_incident_id'), 'briefs', ['incident_id'], unique=False)
    op.create_table('eval_case_results',
    sa.Column('eval_run_id', sa.UUID(), nullable=False),
    sa.Column('eval_case_id', sa.UUID(), nullable=False),
    sa.Column('retrieved_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('rank_of_first_hit', sa.Integer(), nullable=True),
    sa.Column('groundedness', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['eval_case_id'], ['eval_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['eval_run_id'], ['eval_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_case_results_eval_case_id'), 'eval_case_results', ['eval_case_id'], unique=False)
    op.create_index(op.f('ix_eval_case_results_eval_run_id'), 'eval_case_results', ['eval_run_id'], unique=False)
    op.create_table('incident_signals',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_strings', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_service_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('time_window', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extracted_by_model', sa.String(length=200), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_signals_incident_id'), 'incident_signals', ['incident_id'], unique=False)
    op.create_table('postmortem_chunks',
    sa.Column('postmortem_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section_label', sa.String(length=200), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['postmortem_id'], ['postmortems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_postmortem_chunks_embedding_hnsw', 'postmortem_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_postmortem_chunks_postmortem_id'), 'postmortem_chunks', ['postmortem_id'], unique=False)
    op.create_index('ix_postmortem_chunks_tsv_gin', 'postmortem_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('postmortem_failure_modes',
    sa.Column('postmortem_id', sa.UUID(), nullable=False),
    sa.Column('failure_mode_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['failure_mode_id'], ['failure_modes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['postmortem_id'], ['postmortems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('postmortem_id', 'failure_mode_id')
    )
    op.create_table('services',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', name='service_tier'), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('repo_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('runbook_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_services_workspace_name')
    )
    op.create_index(op.f('ix_services_workspace_id'), 'services', ['workspace_id'], unique=False)
    op.create_table('agent_run_steps',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_steps_run_id'), 'agent_run_steps', ['run_id'], unique=False)
    op.create_table('brief_feedback',
    sa.Column('brief_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('verdict', sa.Enum('helpful', 'partially', 'unhelpful', name='feedback_verdict'), nullable=False),
    sa.Column('correct_postmortem_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['correct_postmortem_id'], ['postmortems.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brief_feedback_brief_id'), 'brief_feedback', ['brief_id'], unique=False)
    op.create_table('postmortem_facts',
    sa.Column('postmortem_id', sa.UUID(), nullable=False),
    sa.Column('fact_type', sa.Enum('trigger', 'root_cause', 'remediation', 'detection_gap', 'contributing_factor', name='fact_type'), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_chunk_id', sa.UUID(), nullable=False),
    sa.Column('extracted_by_model', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['postmortem_id'], ['postmortems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['postmortem_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postmortem_facts_postmortem_id'), 'postmortem_facts', ['postmortem_id'], unique=False)
    op.create_table('postmortem_services',
    sa.Column('postmortem_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('root_cause', 'affected', 'downstream', name='service_link_role'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['postmortem_id'], ['postmortems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('postmortem_id', 'service_id', 'role')
    )
    op.create_table('service_edges',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('from_service_id', sa.UUID(), nullable=False),
    sa.Column('to_service_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('calls', 'reads_from', 'publishes_to', 'depends_on', name='edge_kind'), nullable=False),
    sa.Column('criticality', sa.Enum('hard', 'soft', name='edge_criticality'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_service_id', 'to_service_id', 'kind', name='uq_service_edges_from_to_kind')
    )
    op.create_index(op.f('ix_service_edges_from_service_id'), 'service_edges', ['from_service_id'], unique=False)
    op.create_index(op.f('ix_service_edges_to_service_id'), 'service_edges', ['to_service_id'], unique=False)
    op.create_index(op.f('ix_service_edges_workspace_id'), 'service_edges', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_edges_workspace_id'), table_name='service_edges')
    op.drop_index(op.f('ix_service_edges_to_service_id'), table_name='service_edges')
    op.drop_index(op.f('ix_service_edges_from_service_id'), table_name='service_edges')
    op.drop_table('service_edges')
    op.drop_table('postmortem_services')
    op.drop_index(op.f('ix_postmortem_facts_postmortem_id'), table_name='postmortem_facts')
    op.drop_table('postmortem_facts')
    op.drop_index(op.f('ix_brief_feedback_brief_id'), table_name='brief_feedback')
    op.drop_table('brief_feedback')
    op.drop_index(op.f('ix_agent_run_steps_run_id'), table_name='agent_run_steps')
    op.drop_table('agent_run_steps')
    op.drop_index(op.f('ix_services_workspace_id'), table_name='services')
    op.drop_table('services')
    op.drop_table('postmortem_failure_modes')
    op.drop_index('ix_postmortem_chunks_tsv_gin', table_name='postmortem_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_postmortem_chunks_postmortem_id'), table_name='postmortem_chunks')
    op.drop_index('ix_postmortem_chunks_embedding_hnsw', table_name='postmortem_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('postmortem_chunks')
    op.drop_index(op.f('ix_incident_signals_incident_id'), table_name='incident_signals')
    op.drop_table('incident_signals')
    op.drop_index(op.f('ix_eval_case_results_eval_run_id'), table_name='eval_case_results')
    op.drop_index(op.f('ix_eval_case_results_eval_case_id'), table_name='eval_case_results')
    op.drop_table('eval_case_results')
    op.drop_index(op.f('ix_briefs_incident_id'), table_name='briefs')
    op.drop_table('briefs')
    op.drop_index(op.f('ix_agent_runs_incident_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_teams_workspace_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_semantic_cache_workspace_id'), table_name='semantic_cache')
    op.drop_index(op.f('ix_semantic_cache_prompt_hash'), table_name='semantic_cache')
    op.drop_table('semantic_cache')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_postmortems_workspace_status', table_name='postmortems')
    op.drop_index(op.f('ix_postmortems_workspace_id'), table_name='postmortems')
    op.drop_table('postmortems')
    op.drop_index(op.f('ix_jobs_workspace_id'), table_name='jobs')
    op.drop_index('ix_jobs_claim_queue', table_name='jobs', postgresql_where=sa.text("status = 'queued'"))
    op.drop_table('jobs')
    op.drop_index('ix_incidents_workspace_status', table_name='incidents')
    op.drop_index(op.f('ix_incidents_workspace_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_failure_modes_workspace_id'), table_name='failure_modes')
    op.drop_table('failure_modes')
    op.drop_index(op.f('ix_eval_runs_workspace_id'), table_name='eval_runs')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_eval_cases_workspace_id'), table_name='eval_cases')
    op.drop_table('eval_cases')
    op.drop_index(op.f('ix_audit_log_workspace_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_api_keys_workspace_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
